FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["LutheranMusicLibrary.Web.csproj", "."]
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
RUN apt-get update && apt-get install -y curl
RUN curl -L -o /app/lutheran_music_planner.db "https://fourwahls-my.sharepoint.com/:u:/p/matt/IQDgQchB99YzQLi9A9J1scadAVOHq4R-H32IVOsQ4Wfd_-8?e=TqCfkv"
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "LutheranMusicLibrary.Web.dll"]